services:
  db:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - mabiblio-data:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
  mabiblio-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
      - '24678:24678'
    volumes:
      - .:/src
      - node_modules:/src/node_modules

volumes:
  mabiblio-data:
    external: true
  node_modules:
