services:
  db:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - mabiblio-data:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password

volumes:
  mabiblio-data:
    external: true
