name: Build, Test and Push

on:
  workflow_dispatch: ~ # déclenchement manuel
  # push:
  #   branches: ['master']
  # pull_request:
  #   branches: ['master']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: action/setup-node@v4
        with:
          node-version: '23.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit

  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/edithmenechi/ma-biblio:latest
            ghcr.io/edithmenechi/ma-biblio:${{ github.sha }}
